//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public int id { get; set; }
        public Nullable<int> iduser { get; set; }
        public string idsanpham { get; set; }
        public string tensanpham { get; set; }
        public string imgurlsanpham { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> dongia { get; set; }
    }
}
