//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlineTradeEntities1 : DbContext
    {
        public onlineTradeEntities1()
            : base("name=onlineTradeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietdonhang> chitietdonhangs { get; set; }
        public virtual DbSet<dangNhapAdmin> dangNhapAdmins { get; set; }
        public virtual DbSet<loaiSP> loaiSPs { get; set; }
        public virtual DbSet<nguoiDung> nguoiDungs { get; set; }
        public virtual DbSet<sanPham> sanPhams { get; set; }
    }
}
