//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClotheShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanPham
    {
        public string danhCho { get; set; }
        public string maSP { get; set; }
        public int maLoai { get; set; }
        public string tenSP { get; set; }
        public int giaBan { get; set; }
        public string dvt { get; set; }
        public int soLuong { get; set; }
        public string hinhDD { get; set; }
    
        public virtual loaiSP loaiSP { get; set; }
    }
}
